2019-01-26 23:52:51 ERROR (MainThread) [homeassistant.components.mqtt] Failed to connect due to exception: [Errno 111] Connection refused
2019-01-26 23:52:56 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to owntracks/#
2019-01-26 23:52:56 ERROR (MainThread) [homeassistant.setup] Error handling when_setup callback for mqtt
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 263, in when_setup
    await when_setup_cb(hass, component)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/owntracks/__init__.py", line 115, in async_connect_mqtt
    context.mqtt_topic, async_handle_mqtt_message, 1)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 319, in async_subscribe
    qos, encoding)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 701, in async_subscribe
    await self._async_perform_subscription(topic, qos)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 736, in _async_perform_subscription
    _raise_on_error(result)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 821, in _raise_on_error
    'Error talking to MQTT: {}'.format(mqtt.error_string(result_code)))
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
2019-01-26 23:52:56 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to slave/sensor/mitemp_bt_temperature/state
2019-01-26 23:52:56 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to slave/sensor/mitemp_bt_humidity/state
2019-01-26 23:52:56 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to slave/sensor/mitemp_bt_battery/state
2019-01-26 23:52:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 350, in _async_add_entity
    await entity.async_added_to_hass()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/sensor.py", line 118, in async_added_to_hass
    await self._subscribe_topics()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/sensor.py", line 178, in _subscribe_topics
    'qos': self._config.get(CONF_QOS)}})
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/subscription.py", line 83, in async_subscribe_topics
    await requested.resubscribe_if_necessary(hass, current)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/subscription.py", line 44, in resubscribe_if_necessary
    self.qos, self.encoding
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 319, in async_subscribe
    qos, encoding)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 701, in async_subscribe
    await self._async_perform_subscription(topic, qos)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 736, in _async_perform_subscription
    _raise_on_error(result)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 821, in _raise_on_error
    'Error talking to MQTT: {}'.format(mqtt.error_string(result_code)))
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
2019-01-26 23:52:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 350, in _async_add_entity
    await entity.async_added_to_hass()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/sensor.py", line 118, in async_added_to_hass
    await self._subscribe_topics()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/sensor.py", line 178, in _subscribe_topics
    'qos': self._config.get(CONF_QOS)}})
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/subscription.py", line 83, in async_subscribe_topics
    await requested.resubscribe_if_necessary(hass, current)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/subscription.py", line 44, in resubscribe_if_necessary
    self.qos, self.encoding
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 319, in async_subscribe
    qos, encoding)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 701, in async_subscribe
    await self._async_perform_subscription(topic, qos)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 736, in _async_perform_subscription
    _raise_on_error(result)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 821, in _raise_on_error
    'Error talking to MQTT: {}'.format(mqtt.error_string(result_code)))
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
2019-01-26 23:52:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 350, in _async_add_entity
    await entity.async_added_to_hass()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/sensor.py", line 118, in async_added_to_hass
    await self._subscribe_topics()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/sensor.py", line 178, in _subscribe_topics
    'qos': self._config.get(CONF_QOS)}})
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/subscription.py", line 83, in async_subscribe_topics
    await requested.resubscribe_if_necessary(hass, current)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/subscription.py", line 44, in resubscribe_if_necessary
    self.qos, self.encoding
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 319, in async_subscribe
    qos, encoding)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 701, in async_subscribe
    await self._async_perform_subscription(topic, qos)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 736, in _async_perform_subscription
    _raise_on_error(result)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 821, in _raise_on_error
    'Error talking to MQTT: {}'.format(mqtt.error_string(result_code)))
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
2019-01-26 23:53:05 WARNING (MainThread) [homeassistant.setup] Setup of xiaomi_aqara is taking over 10 seconds.
2019-01-26 23:53:20 ERROR (Thread-2) [homeassistant.components.xiaomi_aqara] No gateway discovered
2019-01-26 23:53:20 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_aqara: Component failed to initialize.
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_moisture is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_temperature is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_light_intensity is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_conductivity is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_conductivity is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_temperature is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_moisture is taking over 10 seconds
2019-01-26 23:53:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_light_intensity is taking over 10 seconds
2019-01-26 23:54:05 ERROR (Thread-11) [homeassistant.components.light.yeelight] Unable to update bulb status: Bulb closed the connection.
2019-01-27 00:33:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_light_intensity is taking over 10 seconds
2019-01-27 00:33:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_moisture is taking over 10 seconds
2019-01-27 00:33:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_temperature is taking over 10 seconds
2019-01-27 00:33:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_conductivity is taking over 10 seconds
2019-01-27 01:09:27 ERROR (Thread-4) [homeassistant.components.light.yeelight] Unable to update bulb status: Bulb closed the connection.
2019-01-27 01:13:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_temperature is taking over 10 seconds
2019-01-27 01:13:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_light_intensity is taking over 10 seconds
2019-01-27 01:13:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_moisture is taking over 10 seconds
2019-01-27 01:13:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_conductivity is taking over 10 seconds
2019-01-27 02:24:49 ERROR (Thread-21) [homeassistant.components.light.yeelight] Unable to update bulb status: Bulb closed the connection.
2019-01-27 02:33:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_moisture is taking over 10 seconds
2019-01-27 02:33:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_temperature is taking over 10 seconds
2019-01-27 02:33:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_conductivity is taking over 10 seconds
2019-01-27 02:33:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_light_intensity is taking over 10 seconds
2019-01-27 02:42:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.xiaomi_vacuum_cleaner is taking over 10 seconds
2019-01-27 02:42:28 ERROR (Thread-2) [miio.device] Unable to discover a device at address 192.168.0.122
2019-01-27 02:42:28 WARNING (Thread-2) [homeassistant.components.vacuum.xiaomi_miio] Got exception while fetching the state: Unable to discover the device 192.168.0.122
2019-01-27 03:13:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_conductivity is taking over 10 seconds
2019-01-27 03:13:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_light_intensity is taking over 10 seconds
2019-01-27 03:13:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_temperature is taking over 10 seconds
2019-01-27 03:13:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_moisture is taking over 10 seconds
2019-01-27 05:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_conductivity is taking over 10 seconds
2019-01-27 05:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_light_intensity is taking over 10 seconds
2019-01-27 05:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_temperature is taking over 10 seconds
2019-01-27 05:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_moisture is taking over 10 seconds
2019-01-27 05:53:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_light_intensity is taking over 10 seconds
2019-01-27 05:53:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_temperature is taking over 10 seconds
2019-01-27 05:53:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_moisture is taking over 10 seconds
2019-01-27 05:53:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_conductivity is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_conductivity is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_light_intensity is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_temperature is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_light_intensity is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_conductivity is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_moisture is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_temperature is taking over 10 seconds
2019-01-27 07:13:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_moisture is taking over 10 seconds
2019-01-27 09:58:02 ERROR (Thread-10) [homeassistant.components.light.yeelight] Unable to update bulb status: Bulb closed the connection.
2019-01-27 10:18:40 ERROR (Thread-10) [homeassistant.components.light.yeelight] Unable to update bulb status: Bulb closed the connection.
2019-01-27 10:33:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_conductivity is taking over 10 seconds
2019-01-27 10:33:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_moisture is taking over 10 seconds
2019-01-27 10:33:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_temperature is taking over 10 seconds
2019-01-27 10:33:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_light_intensity is taking over 10 seconds
2019-01-27 11:53:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_temperature is taking over 10 seconds
2019-01-27 11:53:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_moisture is taking over 10 seconds
2019-01-27 11:53:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_conductivity is taking over 10 seconds
2019-01-27 11:53:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.calluna_vulgaris_light_intensity is taking over 10 seconds
2019-01-27 11:53:56 WARNING (Thread-10) [homeassistant.components.climate.eq3btsmart] Updating the state failed: Failed to connect to peripheral 00:1A:22:0F:D0:72, addr type: public
2019-01-27 12:17:15 WARNING (Thread-7) [homeassistant.components.climate.eq3btsmart] Updating the state failed: Failed to connect to peripheral 00:1A:22:0F:D0:72, addr type: public
2019-01-27 13:13:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_light_intensity is taking over 10 seconds
2019-01-27 13:13:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_temperature is taking over 10 seconds
2019-01-27 13:13:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_moisture is taking over 10 seconds
2019-01-27 13:13:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sukulencik_conductivity is taking over 10 seconds
2019-01-27 13:51:32 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for vacuum.xiaomi_vacuum_cleaner (<class 'homeassistant.components.vacuum.xiaomi_miio.MiroboVacuum'>) took 4.786 seconds. Please report platform to the developers at https://goo.gl/Nvioub
2019-01-27 13:53:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_conductivity is taking over 10 seconds
2019-01-27 13:53:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_moisture is taking over 10 seconds
2019-01-27 13:53:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_temperature is taking over 10 seconds
2019-01-27 13:53:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_benjamina_light_intensity is taking over 10 seconds
